import {Link} from './D3Test';
import {Node} from './D3Test';

interface GraphData {
  nodes: Node[];
  links: Link[];
}


export const data: GraphData = {
  nodes: [
    { id: "Data Assets", nodeId: "root", group: "Root", value: 100000, cluster: "root" },
    { id: "Airport", nodeId: "l1-Airport", group: "Category", value: 1000, cluster: "l1-Airport" },
    { id: "Geography", nodeId: "l2-Airport-Geography", group: "Subcategory", value: 250, cluster: "l1-Airport" },
    { id: "Station Details", nodeId: "l2-Airport-Station Details", group: "Subcategory", value: 250, cluster: "l1-Airport" },
    { id: "Domestic /International", nodeId: "l2-Airport-Domestic/International", group: "Subcategory", value: 250, cluster: "l1-Airport" },
    { id: "Aircraft", nodeId: "l1-Aircraft", group: "Category", value: 1200, cluster: "l1-Aircraft" },
    { id: "Registration", nodeId: "l2-Aircraft-Registration", group: "Subcategory", value: 300, cluster: "l1-Aircraft" },
    { id: "Seating Plan", nodeId: "l2-Aircraft-Seating Plan", group: "Subcategory", value: 300, cluster: "l1-Aircraft" },
    { id: "Aircraft Type", nodeId: "l2-Aircraft-Aircraft Type", group: "Subcategory", value: 300, cluster: "l1-Aircraft" },
    { id: "Utilization", nodeId: "l2-Aircraft-Utilization", group: "Subcategory", value: 300, cluster: "l1-Aircraft" },
    { id: "Customer", nodeId: "l1-Customer", group: "Category", value: 2400, cluster: "l1-Customer" },
    { id: "Customer Profile", nodeId: "l2-Customer-Profile", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Booking History", nodeId: "l2-Customer-Booking History", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Booking Behaviours", nodeId: "l2-Customer-Booking Behaviours", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Hotel Bookings", nodeId: "l2-Customer-Hotel Bookings", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Ancillary Preferences", nodeId: "l2-Customer-Ancillary Preferences", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Customer Experience /NPS", nodeId: "l2-Customer-Customer Experience/NPS", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Booking Channels", nodeId: "l2-Customer-Booking Channels", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Customer Flown", nodeId: "l2-Customer-Customer Flown", group: "Subcategory", value: 300, cluster: "l1-Customer" },
    { id: "Employee", nodeId: "l1-Employee", group: "Category", value: 1250, cluster: "l1-Employee" },
    { id: "Employee Profile", nodeId: "l2-Employee-Profile", group: "Subcategory", value: 250, cluster: "l1-Employee" },
    { id: "Headcount", nodeId: "l2-Employee-Headcount", group: "Subcategory", value: 250, cluster: "l1-Employee" },
    { id: "Attrition", nodeId: "l2-Employee-Attrition", group: "Subcategory", value: 250, cluster: "l1-Employee" },
    { id: "Diversity", nodeId: "l2-Employee-Diversity", group: "Subcategory", value: 250, cluster: "l1-Employee" },
    { id: "Span of Control", nodeId: "l2-Employee-Span of Control", group: "Subcategory", value: 250, cluster: "l1-Employee" },
    { id: "Cargo", nodeId: "l1-Cargo", group: "Category", value: 1000, cluster: "l1-Cargo" },
    { id: "Freighters", nodeId: "l2-Cargo-Freighters", group: "Subcategory", value: 250, cluster: "l1-Cargo" },
    { id: "Category", nodeId: "l2-Cargo-Category", group: "Subcategory", value: 250, cluster: "l1-Cargo" },
    { id: "Cargo Agent Performances", nodeId: "l2-Cargo-Cargo Agent Performances", group: "Subcategory", value: 250, cluster: "l1-Cargo" },
    { id: "Freighter Tonnage /Volumes", nodeId: "l2-Cargo-Freighter Tonnage/Volumes", group: "Subcategory", value: 250, cluster: "l1-Cargo" },
    { id: "Crew", nodeId: "l1-Crew", group: "Category", value: 1250, cluster: "l1-Crew" },
    { id: "Roaster", nodeId: "l2-Crew-Roaster", group: "Subcategory", value: 250, cluster: "l1-Crew" },
    { id: "Block Hours", nodeId: "l2-Crew-Block Hours", group: "Subcategory", value: 250, cluster: "l1-Crew" },
    { id: "Crew Qualification", nodeId: "l2-Crew-Crew Qualification", group: "Subcategory", value: 250, cluster: "l1-Crew" },
    { id: "Crew Base Station", nodeId: "l2-Crew-Crew Base Station", group: "Subcategory", value: 250, cluster: "l1-Crew" },
    { id: "Crew NPS", nodeId: "l2-Crew-Crew NPS", group: "Subcategory", value: 250, cluster: "l1-Crew" },
    { id: "Bluechip", nodeId: "l1-Bluechip", group: "Category", value: 300, cluster: "l1-Bluechip" },
    { id: "Sales", nodeId: "l1-Sales", group: "Category", value: 2250, cluster: "l1-Sales" },
    { id: "Revenue", nodeId: "l2-Sales-Revenue", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Routes", nodeId: "l2-Sales-Routes", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Product Class", nodeId: "l2-Sales-Product Class", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Connections", nodeId: "l2-Sales-Connections", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Cancellations", nodeId: "l2-Sales-Cancellations", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Channel", nodeId: "l2-Sales-Channel", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Baggage Details", nodeId: "l2-Sales-Baggage Details", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Sales Agent Performances", nodeId: "l2-Sales-Sales Agent Performances", group: "Subcategory", value: 250, cluster: "l1-Sales" },
    { id: "Flight", nodeId: "l1-Flight", group: "Category", value: 2000, cluster: "l1-Flight" },
    { id: "Schedules", nodeId: "l2-Flight-Schedules", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "Sectors", nodeId: "l2-Flight-Sectors", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "Codeshare", nodeId: "l2-Flight-Codeshare", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "Network", nodeId: "l2-Flight-Network", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "OTP", nodeId: "l2-Flight-OTP", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "Load Factor", nodeId: "l2-Flight-Load Factor", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "Distruptions", nodeId: "l2-Flight-Distruptions", group: "Subcategory", value: 250, cluster: "l1-Flight" },
    { id: "Flight Block Hours", nodeId: "l2-Flight-Block Hours", group: "Subcategory", value: 250, cluster: "l1-Flight" }
  ],
  links: [
    { source: "Data Assets", target: "Airport", value: 2 },
    { source: "Airport", target: "Geography", value: 2 },
    { source: "Airport", target: "Station Details", value: 2 },
    { source: "Airport", target: "Domestic /International", value: 2 },
    { source: "Data Assets", target: "Aircraft", value: 2 },
    { source: "Aircraft", target: "Registration", value: 2 },
    { source: "Aircraft", target: "Seating Plan", value: 2 },
    { source: "Aircraft", target: "Aircraft Type", value: 2 },
    { source: "Aircraft", target: "Utilization", value: 2 },
    { source: "Data Assets", target: "Customer", value: 2 },
    { source: "Customer", target: "Customer Profile", value: 2 },
    { source: "Customer", target: "Booking History", value: 2 },
    { source: "Customer", target: "Booking Behaviours", value: 2 },
    { source: "Customer", target: "Hotel Bookings", value: 2 },
    { source: "Customer", target: "Ancillary Preferences", value: 2 },
    { source: "Customer", target: "Customer Experience /NPS", value: 2 },
    { source: "Customer", target: "Booking Channels", value: 2 },
    { source: "Customer", target: "Customer Flown", value: 2 },
    { source: "Data Assets", target: "Employee", value: 2 },
    { source: "Employee", target: "Employee Profile", value: 2 },
    { source: "Employee", target: "Headcount", value: 2 },
    { source: "Employee", target: "Attrition", value: 2 },
    { source: "Employee", target: "Diversity", value: 2 },
    { source: "Employee", target: "Span of Control", value: 2 },
    { source: "Data Assets", target: "Cargo", value: 2 },
    { source: "Cargo", target: "Freighters", value: 2 },
    { source: "Cargo", target: "Category", value: 2 },
    { source: "Cargo", target: "Cargo Agent Performances", value: 2 },
    { source: "Cargo", target: "Freighter Tonnage /Volumes", value: 2 },
    { source: "Data Assets", target: "Crew", value: 2 },
    { source: "Crew", target: "Roaster", value: 2 },
    { source: "Crew", target: "Block Hours", value: 2 },
    { source: "Crew", target: "Crew Qualification", value: 2 },
    { source: "Crew", target: "Crew Base Station", value: 2 },
    { source: "Crew", target: "Crew NPS", value: 2 },
    { source: "Data Assets", target: "Bluechip", value: 2 },
    { source: "Data Assets", target: "Sales", value: 2 },
    { source: "Sales", target: "Revenue", value: 2 },
    { source: "Sales", target: "Routes", value: 2 },
    { source: "Sales", target: "Product Class", value: 2 },
    { source: "Sales", target: "Connections", value: 2 },
    { source: "Sales", target: "Cancellations", value: 2 },
    { source: "Sales", target: "Channel", value: 2 },
    { source: "Sales", target: "Baggage Details", value: 2 },
    { source: "Sales", target: "Sales Agent Performances", value: 2 },
    { source: "Data Assets", target: "Flight", value: 2 },
    { source: "Flight", target: "Schedules", value: 2 },
    { source: "Flight", target: "Sectors", value: 2 },
    { source: "Flight", target: "Codeshare", value: 2 },
    { source: "Flight", target: "Network", value: 2 },
    { source: "Flight", target: "OTP", value: 2 },
    { source: "Flight", target: "Load Factor", value: 2 },
    { source: "Flight", target: "Distruptions", value: 2 },
    { source: "Flight", target: "Flight Block Hours", value: 2 }
  ]
};